# Generated by Django 3.2.8 on 2021-10-21 00:44

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211020_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(default='/media/image/avatar.png', upload_to=account.models.img_path),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
