# Generated by Django 3.2.8 on 2021-10-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211021_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
