# Generated by Django 3.2.8 on 2021-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profilemodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='username'),
        ),
    ]
