# Generated by Django 3.2.8 on 2021-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211022_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
