# Generated by Django 3.2.8 on 2021-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roommessagemodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessagemodel',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
